### ISSUE TITLE
qinvideo怎么安装

### ISSUE THREAD

**Issue by zuiazuia** [qinvz/qinvideo#1]
你好，qinmei！qinvideo要怎么安装，我在github下载完，好像没办法启动啊

**Comment by qinvz** [comment]
用nodejs启动

**Comment by qinvz** [comment]
此外数据库是mongodb, 用户名与密码都在config.js里面设置

**Comment by zuiazuia** [comment]
数据库本地配置后，然后node app.js ，数据库连接成功，然后启动9000端口，这个都是没问题，但是localhost:9000/auth/register或者其他路由打开后的页面都是Not Found？就是这个不知道为什么？

**Comment by qinvz** [comment]
因为这只是后台api系统，仅用于提供接口，页面的静态文件在public里面，要用nginx代理启用，整个的流程还没打通，配置起来会有点麻烦，简单说就是/qinmei/的请求都转发到public/backend里面去

**Comment by zuiazuia** [comment]
好的，谢谢qinmei!
