### ISSUE TITLE
无法注册账号

### ISSUE THREAD

**Issue by a4008793** [qinvz/qinvideo#2]
![image](https://user-images.githubusercontent.com/2549924/59605698-e9a02880-9141-11e9-866a-1c5c74167368.png)

**Comment by qinvz** [comment]
请提供接口返回信息以及测试过数据库连接没问题

**Comment by a4008793** [comment]
点击注册后就显示一个红叉  不显示其他的

**Comment by qinvz** [comment]
..........登录没问题? F12看看网络请求信息, 或者放出你的网址

**Comment by a4008793** [comment]
www.yomantv.com

**Comment by qinvz** [comment]
这是之前的一个BUG, 最新版已经修复了, 更新下然后重启下数据库试试
